### PR TITLE
Regard `--color` / `--no-color`

### PR DESCRIPTION
**Pull request by sol**
(relies on https://github.com/hspec/hspec/blob/main/CHANGES.markdown#changes-in-2110-2023-04-21)

### CODE REVIEW

**Comment by sol** [comment]
@parsonsmatt this is ready to go.

**Review by parsonsmatt — COMMENTED** [review]
Just so I understand correctly - this skips the `hedgehog` color check and instead uses the `hspec` `--color` and `--no-color` options, where `--no-color` strips out the ANSI codes.

Hedgehog's [`detectColor`](https://hackage.haskell.org/package/hedgehog-1.3/docs/src/Hedgehog.Internal.Config.html#detectColor) function does some other logic, though, like `HEDGEHOG_COLOR` env var check and ensuring the logged in user isn't `mth` lol. 

I feel like we can retain the functionality here with a much broader range of `hspec` versions by detecting color as-is, and then use CPP to use either `Reason` or `ColorizedReason`.

I'm hesitant to force consumers to upgrade to the latest `hspec` versions only for this

**Comment by sol** [comment]
> Just so I understand correctly - this skips the `hedgehog` color check and instead uses the `hspec` `--color` and `--no-color` options, where `--no-color` strips out the ANSI codes.

Correct.

> Hedgehog's [`detectColor`](https://hackage.haskell.org/package/hedgehog-1.3/docs/src/Hedgehog.Internal.Config.html#detectColor) function does some other logic, though, like `HEDGEHOG_COLOR` env var check and ensuring the logged in user isn't `mth` lol.
> 
> I feel like we can retain the functionality here with a much broader range of `hspec` versions by detecting color as-is, and then use CPP to use either `Reason` or `ColorizedReason`.

If I understand you correctly, then no, I don't think that would solve my use case. If I specify `--color` and e.g. redirect `stdout` then `detectColor` will return `False`. As a consequence I will end up without colors, even though I requested them.

> I'm hesitant to force consumers to upgrade to the latest `hspec` versions only for this

Do you think there is any tangible benefit from doing this, that is relevant enough to offsets the additional complexity? Note that existing users can continue to use `0.0.1.2` with older versions of `hspec`.

**Comment by sol** [comment]
@parsonsmatt any chance to get this merged sometime soon?  Maintaining and using my  private fork, which is not on Hackage, will eventually be too much overhead for me.

**Comment by parsonsmatt** [comment]
Sure - please make a version bump and changelog entry and I'll have it released asap. Thanks!

**Comment by sol** [comment]
> Sure - please make a version bump and changelog entry and I'll have it released asap. Thanks!

Done as a separate PR (#27) to not unnecessarily cause conflicts.

**Pull request merged**
